# Generated by Django 2.1.7 on 2019-02-23 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_code', models.CharField(blank=True, help_text='School Code by which it is unique', max_length=255, null=True)),
                ('school_name', models.CharField(blank=True, help_text='School Name full', max_length=255, null=True)),
                ('school_address_line1', models.CharField(blank=True, help_text='School address line 1', max_length=255, null=True)),
                ('school_address_line2', models.CharField(blank=True, help_text='School Address line 2', max_length=255, null=True)),
                ('school_city', models.CharField(blank=True, help_text='School City in which it is located.', max_length=255, null=True)),
                ('school_state', models.CharField(blank=True, help_text='School state in which it is located.', max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, help_text="School Area's pincode.", max_length=255, null=True)),
                ('school_principal_name', models.CharField(blank=True, help_text="School's prinicipal name.", max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text="Student's full name", max_length=255, null=True)),
                ('father_name', models.CharField(blank=True, help_text="Father's name of student.", max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, help_text="Mother's name of student.", max_length=255, null=True)),
                ('studying_class', models.CharField(blank=True, help_text='Class in which student is currently studying.', max_length=10, null=True)),
                ('section', models.CharField(blank=True, help_text='Section of class in which student is currently studying.', max_length=10, null=True)),
                ('id_card_photo', models.ImageField(blank=True, help_text="Student's ID card photo that has been uploaded by Photographer.", max_length=255, null=True, upload_to='images_idcardphoto')),
                ('school_name', models.CharField(blank=True, help_text="Student's school name.", max_length=255, null=True)),
                ('school_address_full', models.CharField(blank=True, help_text="Student's School complete address.", max_length=524, null=True)),
                ('mobile_number', models.CharField(blank=True, help_text="Student's mobile number.", max_length=20, null=True)),
                ('email', models.CharField(blank=True, help_text="Student's email id.", max_length=255, null=True)),
                ('user', models.ForeignKey(help_text='User Relationship with this model.', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
