# Generated by Django 2.1.7 on 2019-02-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schoolinformation_studentinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, help_text='Email of the person who is giving feedback on the system.', max_length=255, null=True)),
                ('name', models.CharField(blank=True, help_text='Name of the person who is giving feedback on the system.', max_length=255, null=True)),
                ('message', models.CharField(blank=True, help_text='Message of the person who is giving feedback on the system.', max_length=255, null=True)),
            ],
        ),
    ]
