# Generated by Django 2.1.7 on 2019-02-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.CharField(blank=True, help_text='Message of the person who is giving feedback on the system.', max_length=1055, null=True),
        ),
    ]
