# Generated by Django 2.1.7 on 2019-02-25 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190225_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified_by_student', models.BooleanField(default=False)),
                ('student_information', models.ForeignKey(help_text='Student Information model Relationship', on_delete=django.db.models.deletion.DO_NOTHING, to='core.StudentInformation')),
                ('user', models.ForeignKey(help_text='User model Relationship', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
