# Generated by Django 2.1.7 on 2019-02-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_verificationcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentinformation',
            unique_together={('user', 'full_name', 'father_name', 'email')},
        ),
    ]
